// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fypzhxrolbeettesaphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5cHpoeHJvbGJlZXR0ZXNhcGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1NDIwNjMsImV4cCI6MjA3OTExODA2M30.4OwIw39x-hBRrxQ9wNM95NvQSQu2nVINXwQclzf5wKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});